---
- name: Prepare Kubernetes nodes
  hosts: kube_nodes
  become: true
  become_method: sudo
  vars:
    kubernetes_apt_release: "https://pkgs.k8s.io/core:/stable:/v1.28"
    kubernetes_packages:
      - kubelet
      - kubeadm
      - kubectl
  tasks:
    - name: Ensure APT dependencies are installed
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: Ensure apt keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes apt repository key
      ansible.builtin.get_url:
        url: "{{ kubernetes_apt_release }}/deb/Release.key"
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: '0644'

    - name: Convert repository key to GPG format
      ansible.builtin.command:
        cmd: >
          gpg --dearmor --yes
          --output /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          /etc/apt/keyrings/kubernetes-apt-keyring.asc
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      register: convert_gpg
      changed_when: convert_gpg.rc == 0

    - name: Configure Kubernetes apt repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        mode: '0644'
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] {{ kubernetes_apt_release }}/deb/ /

    - name: Update apt cache after adding Kubernetes repository
      ansible.builtin.apt:
        update_cache: true

    - name: Install Kubernetes components
      ansible.builtin.apt:
        name: "{{ kubernetes_packages }}"
        state: present
        update_cache: true

    - name: Verify Kubernetes binaries are present
      ansible.builtin.command: "which {{ item }}"
      loop:
        - kubectl
        - kubeadm
        - kubelet
      register: kubernetes_binaries_check
      changed_when: false

    - name: Hold Kubernetes packages at current version
      ansible.builtin.shell: "apt-mark hold {{ item }}"
      args:
        warn: false
      loop: "{{ kubernetes_packages }}"
      register: hold_result
      changed_when: "'marking' in hold_result.stdout.lower() or hold_result.rc == 0"

    - name: Enable kubelet service
      ansible.builtin.systemd:
        name: kubelet
        enabled: true
        state: started

    - name: Optionally set hostname when provided
      ansible.builtin.hostname:
        name: "{{ node_hostname }}"
      when: node_hostname is defined

    - name: Ensure swap is disabled
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb | default(0) | int > 0
      changed_when: false
